name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [
      opened,
      reopened,
      synchronize,
      ready_for_review
    ]
  release:
    types: [published]
  workflow_dispatch:

env:
  MAIN_PYTHON_VERSION: "3.10"
  POETRY_HTTP_BASIC_SOLUTIONS_PRIVATE_PYPI_USERNAME: "PAT"
  POETRY_HTTP_BASIC_SOLUTIONS_PRIVATE_PYPI_PASSWORD: ${{ secrets.SOLUTIONS_PRIVATE_PYPI_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  check-copyright:
    name: Check copyright
    runs-on: [ubuntu-latest]
    steps:
      - name: Check copyright
        uses: Solution-Applications/actions/check-copyright@v6
        with:
          gh-token: ${{ secrets.WORKFLOW_TOKEN }}

  check-code-style:
    name: Check code style
    runs-on: [ubuntu-latest]
    steps:
      - name: Check code style
        uses: Solution-Applications/actions/check-code-style@v6
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          gh-token: ${{ secrets.WORKFLOW_TOKEN }}

  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Build
        uses: Solution-Applications/actions/build@v6
        with:
          artifact-name: "wheel"
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          gh-token: ${{ secrets.WORKFLOW_TOKEN }}
          